#
# Travis CI configuration
#
# Simply tests that Home Assistant configuration is valid.
#
# @link https://home-assistant.io/docs/ecosystem/backup/backup_github/#step-7-configuration-file-testing
#

language: python

python:
  - "3.9"

branches:
  only:
  - master

before_install:
  - cp secrets_dummy.yaml secrets.yaml
  - cp GoogleAssistant-key_dummy.json GoogleAssistant-key.json
  - touch home-assistant_v2.db
  - touch home-assistant.log

install:
  - pip3 install homeassistant

script:
- hass --script check_config -c . -f