- id: '1606926697561'
  alias: Home Assistant - Startup automation
  description: Sends push notification to OnePlus when HA is started and turns ons
    cameras.
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.rens
    data:
      title: HA Started
      message: Home Assistant succesfully Started
      data:
        channel: System
        importance: low
  - service: camera.turn_on
    data: {}
    target:
      area_id:
      - babykamer
      - zolder
      - 2bf8bf6a88fe7668c26a7c9d15f993e9
  mode: single
- id: '1606926764664'
  alias: Home Assistant - Stop notification
  description: Sends push notification to OnePlus when HA is shutdown
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: notify.rens
    data:
      title: HA Stopped
      message: Home Assistant was Stopped
      data:
        channel: System
        importance: low
  mode: single
- id: '1607178039348'
  alias: Alarm - Trigger the Alarm (Motion)
  description: Triggers the Alarm on Motion detection
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.woonkamer_movement
    - binary_sensor.eetkamer_movement
    - binary_sensor.keuken_movement
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state:
      - armed_away
      - armed_night
    - condition: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      state:
      - docked
      - unavailable
  action:
  - service: alarm_control_panel.alarm_trigger
    data: {}
    entity_id: alarm_control_panel.ha_alarm
  mode: single
- id: '1607443881376'
  alias: Alarm - Alarm Pending
  description: Play alarm pending sound and show security page on Nest Hub
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: pending
  condition: []
  action:
  - service: notify.all_devices
    data:
      title: Alarm
      message: Het alarm zal over 60 seconden afgaan!
      data:
        channel: Alarm
        importance: high
        actions:
        - action: alarm_disarm
          title: Alarm uitschakelen
        - action: URI
          title: Open Alarm Paneel
          uri: lovelace/security
  - service: media_player.play_media
    data:
      media_content_id: https://home.rensverhagen.nl/local/AlarmPending60.mp3
      media_content_type: audio/mp3
    entity_id: media_player.google_home
  - service: script.show_alarm_panel
  mode: single
- id: '1607444176030'
  alias: Alarm - Alarm Triggered
  description: Play alarm sound and sent notification to mobile
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: triggered
  condition: []
  action:
  - service: notify.all_devices
    data:
      title: Alarm
      message: Het alarm is afgegaan!
      data:
        channel: Alarm
        importance: high
        actions:
        - action: alarm_disarm
          title: Alarm uitschakelen
        - action: URI
          title: Open Alarm Paneel
          uri: lovelace/security
  - service: media_player.play_media
    entity_id: media_player.google_home
    data:
      media_content_id: https://home.rensverhagen.nl/local/Alarm.mp3
      media_content_type: audio/mp3
  mode: single
- id: '1607601953191'
  alias: Lights - Eetkamer Turn on
  description: Turns on lights in Eetkamer when it is dark and motion is detected
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.eetkamer_movement
    - binary_sensor.achterdeur
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.eetkamer_lightlevel
    below: '100'
  - condition: state
    entity_id: light.eetkamer
    state: 'off'
    for:
      seconds: 10
  action:
  - service: light.turn_on
    entity_id: light.eetkamer
    data:
      brightness_pct: 90
  mode: single
- id: '1607602424829'
  alias: Lights - Woonkamer Turn on
  description: Turns on lights in Woonkamer when it is dark and motion is detected.
  trigger:
  - platform: state
    entity_id: binary_sensor.woonkamer_movement
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.woonkamer_lightlevel
    below: '100'
  - condition: state
    entity_id: light.woonkamer
    state: 'off'
    for:
      seconds: 10
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.woonkamer
  mode: single
- id: '1607689290224'
  alias: Test Automation
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.test_toggle
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: notify.rens
    data:
      title: Test
      message: 'from: ''off'' to: ''on'''
  mode: single
- id: '1607713120959'
  alias: 'Input Boolean: Sleep - Turn off'
  description: Turn off Input Sleep Boolean when motion is detected
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.woonkamer_movement
    - binary_sensor.eetkamer_movement
    - binary_sensor.keuken_movement
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  action:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.sleeping
  mode: single
- id: '1608586872962'
  alias: Lights - Eetkamer Turn off
  description: Turns off lights in Eetkamer when no precense is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.eetkamer_presence
    to: 'off'
    for:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  condition:
  - condition: state
    entity_id: light.eetkamer
    state: 'on'
    for: 0:01:00
  action:
  - service: light.turn_off
    entity_id: light.eetkamer
  mode: single
- id: '1608601873724'
  alias: Kerstboom aanzetten
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.woonkamer_presence
    from: 'off'
    to: 'on'
  condition:
  - condition: device
    type: is_off
    device_id: abc82ed7f7764c4685f1998658cb6b08
    entity_id: switch.smart_switch_1
    domain: switch
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.smart_switch_1
  mode: single
- id: '1608745478499'
  alias: Lights - Keuken Turn on
  description: Turns on lights in Keuken when it is dark and motion is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.keuken_movement
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.keuken_lightlevel
    below: '100'
  - condition: state
    entity_id: light.keuken
    state: 'off'
    for:
      seconds: 10
  action:
  - service: light.turn_on
    entity_id: light.keuken
    data:
      brightness_pct: 85
  mode: single
- id: '1608745639683'
  alias: Lights - Keuken Turn off
  description: Turns off lights in Keuken when no presence is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.keuken_presence
    to: 'off'
    for:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  condition:
  - condition: state
    entity_id: light.keuken
    state: 'on'
    for: 0:01:00
  action:
  - service: light.turn_off
    entity_id: light.keuken
  mode: single
- id: '1610579086841'
  alias: Alarm - Trigger the Alarm (Doors)
  description: Triggers the Alarm only on door sensors
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.achterdeur
    - binary_sensor.voordeur
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state:
    - armed_night
    - armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    data: {}
    entity_id: alarm_control_panel.ha_alarm
  mode: single
- id: '1610579800442'
  alias: Climate - Zolder Heating Turn off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.zolderkamer_temperature
    above: 20.5
  condition:
  - condition: state
    entity_id: switch.smart_switch_1
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.smart_switch_1
  mode: single
- id: '1627808388677'
  alias: Cleanup - Vacuum Daily
  description: Start Xiaomi Roborock cleanup when we're sleeping and last cleanup
    was > 1 day ago
  trigger:
  - platform: time
    at: input_datetime.cleanup_time
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'on'
    - condition: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      attribute: status
      state:
      - Docked
      - Charging
  action:
  - device_id: 63e78c663d8faa6db81dd0f4298c673b
    domain: vacuum
    entity_id: vacuum.xiaomi_vacuum_cleaner
    type: clean
  mode: single
- id: '1627817145776'
  alias: Cleanup - Set Last Cleanup Time
  description: Set last cleanup time if cleaned more than 30 minutes.
  trigger:
  - platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    attribute: status
    for: 00:30:00
    to: Cleaning
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      datetime: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.last_cleanup
  mode: single
- id: '1641158665593'
  alias: Car - Unlock Charging Port
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.voordeur
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.model_3_charger_sensor
    state: 'on'
  - condition: numeric_state
    entity_id: sensor.model_3_battery_sensor
    above: '85'
  - condition: state
    entity_id: device_tracker.model_3_location_tracker
    state: home
  action:
  - service: lock.unlock
    target:
      entity_id: lock.model_3_charger_door_lock
  mode: single
- id: '1644962344513'
  alias: Doorbell - Send notification
  description: Send notification when doorbell is pressed to all devices
  trigger:
  - type: turned_on
    platform: device
    device_id: b080a8910a40998b3b6401335df8fc6e
    entity_id: binary_sensor.doorbell
    domain: binary_sensor
  condition: []
  action:
  - service: notify.all_devices
    data:
      title: Ding dong!
      message: Er staat iemand bij de deur
      data:
        channel: Doorbell
        importance: high
        image: /api/camera_proxy/camera.voordeur
        actions:
        - action: URI
          title: Toon camera voordeur
          uri: entityId:camera.voordeur
  - service: camera.turn_on
    data: {}
    target:
      entity_id: camera.voordeur
  mode: single
- id: '1644962908293'
  alias: Doorbell - (De)Activate Chime
  description: Deactivate doorbell chime when we are sleeping and turn on when we
    are awake
  trigger:
  - platform: state
    entity_id: input_boolean.sleeping
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.sleeping
        state: 'on'
      sequence:
      - type: turn_off
        device_id: b080a8910a40998b3b6401335df8fc6e
        entity_id: switch.doorbell_chime_active
        domain: switch
    - conditions:
      - condition: state
        entity_id: input_boolean.sleeping
        state: 'off'
      sequence:
      - type: turn_on
        device_id: b080a8910a40998b3b6401335df8fc6e
        entity_id: switch.doorbell_chime_active
        domain: switch
    default: []
  mode: single
- id: '1651602620853'
  alias: Mower - Set Mower state based on Toggle
  description: When helper toggle is set, make sure that the mower is turned on/off
  trigger:
  - platform: state
    entity_id: input_boolean.mower
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.mower
        state: 'on'
      - condition: state
        entity_id: sensor.indego_128604519_mower_state
        state: Docked
      sequence:
      - service: indego.command
        data:
          command: mow
    - conditions:
      - condition: state
        entity_id: input_boolean.mower
        state: 'off'
      - condition: state
        entity_id: sensor.indego_128604519_mower_state
        state: Mowing
      sequence:
      - service: indego.command
        data:
          command: returnToDock
    default: []
  mode: single
- id: '1651605735910'
  alias: Mower - Set Toggle based on Mower state
  description: When mower state changes, make sure that the toggle is is turned on/off
    as well
  trigger:
  - platform: state
    entity_id:
    - sensor.indego_128604519_mower_state
    from: Mowing
    to: Docked
  - platform: state
    entity_id:
    - sensor.indego_128604519_mower_state
    to: Mowing
    from: Docked
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.mower
        state: 'on'
      - condition: state
        entity_id: sensor.indego_128604519_mower_state
        state: Docked
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.mower
    - conditions:
      - condition: state
        entity_id: input_boolean.mower
        state: 'off'
      - condition: state
        entity_id: sensor.indego_128604519_mower_state
        state: Mowing
      sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.mower
    default: []
  mode: single
- id: '1659563358634'
  alias: Waste - Turn on Waste Collector
  description: When waste needs to be picked-up next day, enable waste collector so
    that alerts notifications are sent to all devices.
  trigger:
  - platform: time
    at: '18:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.waste_collect
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.afvalwijzer_next_in_days
    below: '2'
  action:
  - wait_for_trigger:
    - platform: state
      entity_id:
      - input_boolean.home_presence
      to: 'on'
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.waste_collect
  mode: single
- id: '1660266676956'
  alias: Lights - Philips Hue Dimmer Switch - Woonkamer [BLUEPRINT ON]
  description: ''
  use_blueprint:
    path: vanstinator/zha-philips-hue-dimmer-switch-rwl020-rwl021.yaml
    input:
      remote: c0292cc5e66a7cc86d402e11f055c168
      light:
        entity_id: light.woonkamer
      force_brightness: true
      brightness: 60
- id: '1661847323319'
  alias: Lights - Philips Hue Dimmer Switch - Woonkamer [BLUEPRINT OFF]
  description: ''
  use_blueprint:
    path: Jessendelft/hue_dimmer_switchV3.yaml
    input:
      remote: c0292cc5e66a7cc86d402e11f055c168
      light: light.woonkamer
      min_brightness: 0
      button_on_single:
      - service: light.turn_on
        data:
          color_temp: 350
        target:
          entity_id: light.woonkamer
- id: '1661973733840'
  alias: Lights - Schuur Ledstrip Run Colorloop
  description: ''
  use_blueprint:
    path: hugalafutro/Color_Loop.yaml
    input:
      cl_light:
        entity_id:
        - light.schuur_ledstrip_raam
- id: '1662031659290'
  alias: Alarm - Sync Alarm Control Panel States
  description: This automation syncs the HA Alarm state with other alarm panels such
    as the Eufy Cameras
  trigger:
  - platform: state
    entity_id:
    - alarm_control_panel.ha_alarm
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_away
      sequence:
      - service: alarm_control_panel.alarm_arm_away
        data: {}
        target:
          entity_id:
          - alarm_control_panel.dex
          - alarm_control_panel.extra
          - alarm_control_panel.kate
          - alarm_control_panel.homebase
    - conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_night
      sequence:
      - service: alarm_control_panel.alarm_arm_night
        data: {}
        target:
          entity_id:
          - alarm_control_panel.extra
          - alarm_control_panel.homebase
    - conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: disarmed
      sequence:
      - service: alarm_control_panel.alarm_arm_home
        data: {}
        target:
          entity_id:
          - alarm_control_panel.dex
          - alarm_control_panel.extra
          - alarm_control_panel.kate
          - alarm_control_panel.homebase
    default: []
  mode: single
