- id: '1606926697561'
  alias: HA Start notify
  description: Sends push notification to OnePlus when HA is started
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      title: HA Settings
      message: Home Assistant succesfully Started
  mode: single
- id: '1606926764664'
  alias: HA Stop notify
  description: Sends push notification to OnePlus when HA is shutdown
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      title: HA Settings
      message: Home Assistant Stopped
  mode: single
- id: '1607178039348'
  alias: Alarm - Trigger the Alarm
  description: Triggers the Alarm so that follow-up states are automatically set
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.achterdeur
    - binary_sensor.voordeur
    - binary_sensor.woonkamer_presence
    - binary_sensor.eetkamer_presence
    - binary_sensor.keuken_presence
    from: 'off'
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_night
  action:
  - service: alarm_control_panel.alarm_trigger
    data: {}
    entity_id: alarm_control_panel.ha_alarm
  mode: single
- id: '1607443881376'
  alias: Alarm - Alarm Pending
  description: Play alarm pending sound and show security page on Nest Hub
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: pending
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      title: Alarm
      message: Het alarm zal over 60 seconden afgaan!
      data:
        actions:
        - action: alarm_disarm
          title: Alarm uitschakelen
        - action: URI
          title: Open Alarm Paneel
          uri: lovelace/security
  - service: media_player.play_media
    data:
      media_content_id: https://home.rensverhagen.nl/local/AlarmPending60.mp3
      media_content_type: audio/mp3
    entity_id: media_player.google_home
  mode: single
- id: '1607444176030'
  alias: Alarm - Alarm Triggered
  description: Play alarm sound and sent notification to mobile
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: triggered
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      title: Alarm
      message: Het alarm is afgegaan!
      data:
        actions:
        - action: alarm_disarm
          title: Alarm uitschakelen
        - action: URI
          title: Open Alarm Paneel
          uri: lovelace/security
  - service: media_player.play_media
    entity_id: media_player.google_home
    data:
      media_content_id: https://home.rensverhagen.nl/local/Alarm.mp3
      media_content_type: audio/mp3
  mode: single
- id: '1607601953191'
  alias: 'Lights - Turn on Eetkamer '
  description: Turns on lights in Eetkamer when it is dark and motion is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.eetkamer_presence
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.eetkamer_lightlevel
    below: '100'
  - condition: state
    entity_id: light.eetkamer
    state: 'off'
    for:
      minutes: 5
  action:
  - service: light.turn_on
    entity_id: light.eetkamer
    data:
      brightness_pct: 100
  mode: single
- id: '1607602424829'
  alias: Lights - Turn on Woonkamer
  description: Turns on lights in Woonkamer when it is dark and motion is detected.
  trigger:
  - platform: state
    entity_id: binary_sensor.woonkamer_presence
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.woonkamer_lightlevel
    below: '100'
  - condition: state
    entity_id: light.woonkamer
    state: 'off'
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.woonkamer
  mode: single
- id: '1607689290224'
  alias: Test Automation
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.test_toggle
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      title: Test
      message: 'from: ''off'' to: ''on'''
  mode: single
- id: '1607713120959'
  alias: 'Input Boolean: Sleep - Turn off'
  description: Turn off Input Sleep Boolean when motion is detected
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.woonkamer_presence
    - binary_sensor.eetkamer_presence
    - binary_sensor.keuken_presence
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  action:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.sleeping
  mode: single
- id: '1608586872962'
  alias: Lights - Turn off Eetkamer
  description: Turns off lights in Eetkamer when no motion is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.eetkamer_presence
    to: 'off'
    for: 0:15:00
  condition:
  - condition: state
    entity_id: light.eetkamer
    state: 'on'
    for: 0:30:00
  action:
  - service: light.turn_off
    entity_id: light.eetkamer
  mode: single
- id: '1608601873724'
  alias: Home State - Wake Up
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.sleeping
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.smart_switch_1
  mode: single
- id: '1608745478499'
  alias: Lights - Turn on Keuken
  description: Turns on lights in Keuken when it is dark and motion is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.keuken_presence
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.keuken_lightlevel
    below: '100'
  - condition: state
    entity_id: light.keuken
    state: 'off'
    for:
      minutes: 5
  action:
  - service: light.turn_on
    entity_id: light.keuken
    data:
      brightness_pct: 100
  mode: single
- id: '1608745639683'
  alias: Lights - Turn off Keuken
  description: Turns off lights in Keuken when no motion is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.keuken_presence
    to: 'off'
    for: 0:15:00
  condition:
  - condition: state
    entity_id: light.keuken
    state: 'on'
    for: 0:30:00
  action:
  - service: light.turn_off
    entity_id: light.keuken
  mode: single
