- id: '1587894913273'
  alias: Master Branch Passed
  description: When the Master Branch passes in Travis-CI do a Pull from Github
  trigger:
  - entity_id: sensor.rensverhagen_homeassistant_state
    from: started
    platform: state
    to: passed
  condition: []
  action:
  - data:
      addon: core_git_pull
    service: hassio.addon_start
- id: '1606926697561'
  alias: HA Start notify
  description: Sends push notification to OnePlus when HA is started
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      message: HA Started
  mode: single
- id: '1606926764664'
  alias: HA Stop notify
  description: Sends push notification to OnePlus when HA is shutdown
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      message: HA Stopped
  mode: single
- id: '1607178039348'
  alias: Alarm - Trigger Silent
  description: Sends push notification when alarm is triggered
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.achterdeur
    - binary_sensor.voordeur
    - binary_sensor.woonkamer_presence
    - binary_sensor.eetkamer_presence
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_away
  action:
  - service: notify.all_devices
    data:
      message: ALARM! Stille alarm is afgegaan
  - service: cast.show_lovelace_view
    data:
      dashboard_path: lovelace
      view_path: security
    entity_id: media_player.nest_hub_woonkamer
  mode: single
