- id: '1587894913273'
  alias: Master Branch Passed
  description: When the Master Branch passes in Travis-CI do a Pull from Github
  trigger:
  - entity_id: sensor.rensverhagen_homeassistant_state
    from: started
    platform: state
    to: passed
  condition: []
  action:
  - data:
      addon: core_git_pull
    service: hassio.addon_start
- id: '1606926697561'
  alias: HA Start notify
  description: Sends push notification to OnePlus when HA is started
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      message: HA Started
  mode: single
- id: '1606926764664'
  alias: HA Stop notify
  description: Sends push notification to OnePlus when HA is shutdown
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      message: HA Stopped
  mode: single
- id: '1607178039348'
  alias: Alarm - Trigger the Alarm
  description: Triggers the Alarm so that follow-up states are automatically set
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.achterdeur
    - binary_sensor.voordeur
    - binary_sensor.woonkamer_presence
    - binary_sensor.eetkamer_presence
    from: 'off'
    to: 'on'
  condition:
  - condition: or
    conditions:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_away
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_night
  action:
  - service: alarm_control_panel.alarm_trigger
    data: {}
    entity_id: alarm_control_panel.ha_alarm
  mode: single
- id: '1607443881376'
  alias: Alarm - Alarm Pending
  description: Play alarm pending sound and show security page on Nest Hub
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: pending
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      title: Alarm
      message: Het alarm zal over 60 seconden afgaan!
      data:
        actions:
        - action: alarm_disarm
          title: Alarm uitschakelen
        - action: URI
          title: Open Alarm Paneel
          uri: lovelace/security
  - service: media_player.play_media
    data:
      media_content_id: https://home.rensverhagen.nl/local/AlarmPending60.mp3
      media_content_type: audio/mp3
    entity_id: media_player.google_home
  mode: single
- id: '1607444176030'
  alias: Alarm - Alarm Triggered
  description: Play alarm sound and sent notification to mobile
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: triggered
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      title: Alarm
      message: Het alarm is afgegaan!
      data:
        actions:
        - action: alarm_disarm
          title: Alarm uitschakelen
        - action: URI
          title: Open Alarm Paneel
          uri: lovelace/security
  - service: media_player.play_media
    entity_id: media_player.google_home
    data:
      media_content_id: https://home.rensverhagen.nl/local/Alarm.mp3
      media_content_type: audio/mp3
  mode: single
    data:
      message: ALARM! Stille alarm is afgegaan
  - service: cast.show_lovelace_view
    data:
      dashboard_path: lovelace
      view_path: security
    entity_id: media_player.nest_hub_woonkamer
  mode: single
