- id: '1606926697561'
  alias: HA Start notify
  description: Sends push notification to OnePlus when HA is started
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      title: HA Settings
      message: Home Assistant succesfully Started
  mode: single
- id: '1606926764664'
  alias: HA Stop notify
  description: Sends push notification to OnePlus when HA is shutdown
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      title: HA Settings
      message: Home Assistant Stopped
  mode: single
- id: '1607178039348'
  alias: Alarm - Trigger the Alarm (Motion)
  description: Triggers the Alarm on Motion detection
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.woonkamer_presence
    - binary_sensor.eetkamer_presence
    - binary_sensor.keuken_presence
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: 
      - armed_away
      - armed_night
    - condition: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      state:
      - docked
      - unavailable
  action:
  - service: alarm_control_panel.alarm_trigger
    data: {}
    entity_id: alarm_control_panel.ha_alarm
  mode: single
- id: '1607443881376'
  alias: Alarm - Alarm Pending
  description: Play alarm pending sound and show security page on Nest Hub
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: pending
  condition: []
  action:
  - service: notify.all_devices
    data:
      title: Alarm
      message: Het alarm zal over 60 seconden afgaan!
      data:
        actions:
        - action: alarm_disarm
          title: Alarm uitschakelen
        - action: URI
          title: Open Alarm Paneel
          uri: lovelace/security
  - service: media_player.play_media
    data:
      media_content_id: https://home.rensverhagen.nl/local/AlarmPending60.mp3
      media_content_type: audio/mp3
    entity_id: media_player.google_home
  mode: single
- id: '1607444176030'
  alias: Alarm - Alarm Triggered
  description: Play alarm sound and sent notification to mobile
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: triggered
  condition: []
  action:
  - service: notify.all_devices
    data:
      title: Alarm
      message: Het alarm is afgegaan!
      data:
        actions:
        - action: alarm_disarm
          title: Alarm uitschakelen
        - action: URI
          title: Open Alarm Paneel
          uri: lovelace/security
  - service: media_player.play_media
    entity_id: media_player.google_home
    data:
      media_content_id: https://home.rensverhagen.nl/local/Alarm.mp3
      media_content_type: audio/mp3
  mode: single
- id: '1607601953191'
  alias: Lights - Eetkamer Turn on
  description: Turns on lights in Eetkamer when it is dark and motion is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.eetkamer_presence
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.eetkamer_lightlevel
    below: '100'
  - condition: state
    entity_id: light.eetkamer
    state: 'off'
    for:
      seconds: 10
  action:
  - service: light.turn_on
    entity_id: light.eetkamer
    data:
      brightness_pct: 90
  mode: single
- id: '1607602424829'
  alias: Lights - Woonkamer Turn on
  description: Turns on lights in Woonkamer when it is dark and motion is detected.
  trigger:
  - platform: state
    entity_id: binary_sensor.woonkamer_presence
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.woonkamer_lightlevel
    below: '100'
  - condition: state
    entity_id: light.woonkamer
    state: 'off'
    for:
      seconds: 10
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.woonkamer
  mode: single
- id: '1607689290224'
  alias: Test Automation
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.test_toggle
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: notify.mobile_app_oneplus8
    data:
      title: Test
      message: 'from: ''off'' to: ''on'''
  mode: single
- id: '1607713120959'
  alias: 'Input Boolean: Sleep - Turn off'
  description: Turn off Input Sleep Boolean when motion is detected
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.woonkamer_presence
    - binary_sensor.eetkamer_presence
    - binary_sensor.keuken_presence
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  action:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.sleeping
  mode: single
- id: '1608586872962'
  alias: Lights - Eetkamer Turn off
  description: Turns off lights in Eetkamer when no motion is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.eetkamer_presence
    to: 'off'
    for: 0:15:00
  condition:
  - condition: state
    entity_id: light.eetkamer
    state: 'on'
    for: 0:30:00
  action:
  - service: light.turn_off
    entity_id: light.eetkamer
  mode: single
- id: '1608601873724'
  alias: Kerstboom aanzetten
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.woonkamer_presence
    from: 'off'
    to: 'on'
  condition:
  - condition: device
    type: is_off
    device_id: abc82ed7f7764c4685f1998658cb6b08
    entity_id: switch.smart_switch_1
    domain: switch
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.smart_switch_1
  mode: single
- id: '1608745478499'
  alias: Lights - Keuken Turn on
  description: Turns on lights in Keuken when it is dark and motion is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.keuken_presence
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.keuken_lightlevel
    below: '100'
  - condition: state
    entity_id: light.keuken
    state: 'off'
    for:
      seconds: 10
  action:
  - service: light.turn_on
    entity_id: light.keuken
    data:
      brightness_pct: 85
  mode: single
- id: '1608745639683'
  alias: Lights - Keuken Turn off
  description: Turns off lights in Keuken when no motion is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.keuken_presence
    to: 'off'
    for: 0:15:00
  condition:
  - condition: state
    entity_id: light.keuken
    state: 'on'
    for: 0:30:00
  action:
  - service: light.turn_off
    entity_id: light.keuken
  mode: single
- id: '1610579086841'
  alias: Alarm - Trigger the Alarm (Doors)
  description: Triggers the Alarm only on door sensors
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.achterdeur
    - binary_sensor.voordeur
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: 
    - armed_night
    - armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    data: {}
    entity_id: alarm_control_panel.ha_alarm
  mode: single
- id: '1610579800442'
  alias: Climate - Zolder Heating Turn off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.zolderkamer_temperature
    above: 20.5
  condition:
  - condition: state
    entity_id: switch.smart_switch_1
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.smart_switch_1
  mode: single
- id: '1610900462319'
  alias: Media - Harmony Activity changes
  description: Sets the input select helper to match harmony activity
  trigger:
  - platform: state
    entity_id: remote.harmony_hub
    attribute: current_activity
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.harmony_activity
      option: '{{trigger.to_state.attributes.current_activity}}'
  mode: single
- id: '1610901571774'
  alias: Media - Harmony Input Select changes
  description: 'Sets the harmony activity when input select helper changes '
  trigger:
  - platform: state
    entity_id: input_select.harmony_activity
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: remote.harmony_hub
      attribute: current_activity
      state: '{{trigger.to_state.state}}'
  action:
  - service: remote.turn_on
    data:
      entity_id: remote.harmony_hub
      activity: '{{trigger.to_state.state}}'
  mode: single
