homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude 
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Include homeassistant customizations:
  customize: !include config_files/customize.yaml
  # Internal and External URL 1.10 upgrade
  external_url: !secret hassio_url
  internal_url: !secret hassio_url_internal
  # Trusting localhost and devices on local network
  auth_providers:
  - type: homeassistant
  - type: trusted_networks
    trusted_networks:
     - 127.0.0.1
     - !secret router_ip_range

### Include dependent configuration files ###
automation: !include automations.yaml
automation backend: !include config_files/backend_automations.yaml
script: !include scripts.yaml
person: !include persons.yaml
scene: !include scenes.yaml
group: !include config_files/groups.yaml
sensor: !include config_files/sensor.yaml
input_boolean: !include config_files/input_boolean.yaml
input_select: !include config_files/input_select.yaml
input_number: !include config_files/input_number.yaml
input_text: !include config_files/input_text.yaml
alarm_control_panel: !include config_files/alarm_control_panel.yaml
camera: !include config_files/cameras.yaml

### Include dependent intregration files ###
google_assistant: !include integrations/google_assistant.yaml
influxdb: !include integrations/influxdb.yaml
nest: !include integrations/nest.yaml
notify: !include integrations/notify.yaml
tesla: !include integrations/tesla.yaml
spotify: !include integrations/spotify.yaml
utility_meter: !include integrations/utility_meter.yaml
vacuum: !include integrations/vacuum.yaml
weather: !include integrations/weather.yaml

### Set log level ###
logger:
  default: error
  #log levels critical, fatal, error, warning, warn, info, debug, notset

### Http access setup ###
http:
  server_port: !secret hassio_server_port
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret synology_ip
  ip_ban_enabled: true
  login_attempts_threshold: 20
  # 13-2-2019 RV: Deactivated SSL, because of reverse proxy setup on Synology NAS
  #ssl_certificate: !secret ssl_certificate_location
  #ssl_key: !secret ssl_key_location

### Enables default configuration options ### https://www.home-assistant.io/integrations/default_config/ 
default_config:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Zones
zone:
  name: Work Rens
  latitude: !secret work_rens_latitude
  longitude: !secret work_rens_longitude
  radius: 180
  icon: mdi:worker

# Check if users are at home via netgear router connection 
device_tracker:
  - platform: netgear
    host: !secret router_ip
    username: !secret router_username
    password: !secret router_password
    # Check every minute for new devices
    interval_seconds: 60
    # Wait atleast 5 minutes before setting away status
    consider_home: 0:05
    new_device_defaults:
      track_new_devices: true # New devices will be tracked by default -> change tracking per device in the known_devices.yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'nl'
    base_url: !secret hassio_url

# Stream / FFmpeg, needed for IP Camera access
# stream: // 4-12-2020 RV: Using ffmpeg instead of stream platform for webcam
ffmpeg:

### Hass.io Database ###
# Recorder, controlling where the Logs / Activites are stored
recorder:
  # keep the last 2 weeks of data
  purge_keep_days: 14
  # automatically purge the database every night based on the purge_keep_days, default is true
  # auto_purge: true
  # The max amount of times, the recorder retries to connect to the database
  db_max_retries: 6
  #The time in seconds, that the recorder sleeps when trying to connect to the database
  db_retry_wait: 20
  # data is written to mariadb running on Synology NAS
  ### 22-05-2020 RV: Exclude DB Url to NAS ###
  ### db_url: !secret mariadb_url
  # exclude the following entities of logging:
  # exclude:
  #  entities:
    # Excluding router sensors, deactivated didn't seem to work, so commented exlusion out.
     # - sensor.r7000_gateway_packets_sec_received
     # - sensor.r7000_gateway_bytes_received
     # - sensor.r7000_gateway_bytes_sent
     # - sensor.r7000_gateway_kbyte_sec_received
     # - sensor.r7000_gateway_packets_received
     # - sensor.r7000_gateway_kbyte_sec_sent
     # - sensor.r7000_gateway_packets_sec_sent
     # - sensor.r7000_gateway_packets_sent