homeassistant:
  # Include homeassistant customizations:
  customize: !include config_files/customize.yaml

  # Trusting localhost and devices on local network
  auth_providers:
  - type: homeassistant
  - type: trusted_networks
    trusted_networks:
     - 127.0.0.1
     - !secret router_ip_range

  allowlist_external_dirs:
    - "/media/cameras"

### Include dependent configuration files ###
automation: !include automations.yaml
automation backend: !include config_files/backend_automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include config_files/groups.yaml
sensor: !include config_files/sensor.yaml
alarm_control_panel: !include config_files/alarm_control_panel.yaml
camera: !include config_files/cameras.yaml

### Include dependent intregration files ###
google_assistant: !include integrations/google_assistant.yaml
notify: !include integrations/notify.yaml
alert: !include integrations/alert.yaml
utility_meter: !include integrations/utility_meter.yaml
sonoff: !include integrations/sonoff.yaml
telegram_bot: !include integrations/telegram.yaml

### Set log level ###
### Available log levels: critical, fatal, error, warning, warn, info, debug, notset

logger:
  default: warning
  #logs:
  #  homeassistant.components.webhook: debug

### Http access setup ###
http:
  server_port: !secret hassio_server_port
  ip_ban_enabled: true
  login_attempts_threshold: 15

### Enables default configuration options ### https://www.home-assistant.io/integrations/default_config/ 
default_config:

# Discover some devices automatically
## discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'nl'
    ## base_url: !secret hassio_url

# Stream / FFmpeg, needed for IP Camera access
# stream: // 4-12-2020 RV: Using ffmpeg instead of stream platform for webcam
ffmpeg:

### Hass.io Database ###
# Recorder, controlling where the Logs / Activites are stored
recorder:
  # keep the last 2 weeks of data
  purge_keep_days: 14
  # automatically purge the database every night based on the purge_keep_days, default is true
  # auto_purge: true
  # The max amount of times, the recorder retries to connect to the database
  db_max_retries: 6
  #The time in seconds, that the recorder sleeps when trying to connect to the database
  db_retry_wait: 20
  # data is written to mariadb running on Synology NAS
  ### 22-05-2020 RV: Exclude DB Url to NAS ###
  ### db_url: !secret mariadb_url
  # exclude the following entities of logging:
  # exclude:
  #  entities:
    # Excluding router sensors, deactivated didn't seem to work, so commented exlusion out.
     # - sensor.r7000_gateway_packets_sec_received
     # - sensor.r7000_gateway_bytes_received
     # - sensor.r7000_gateway_bytes_sent
     # - sensor.r7000_gateway_kbyte_sec_received
     # - sensor.r7000_gateway_packets_received
     # - sensor.r7000_gateway_kbyte_sec_sent
     # - sensor.r7000_gateway_packets_sec_sent
     # - sensor.r7000_gateway_packets_sent