homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude 
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Include homeassistant customizations:
  customize: !include config_files/customize.yaml
  # Trusting localhost and devices on local network
  auth_providers:
  - type: homeassistant
  - type: trusted_networks
    trusted_networks:
     - 127.0.0.1
     - !secret router_ip_range

### Include dependent files ###
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
person: !include persons.yaml
scene: !include scenes.yaml
input_boolean: !include config_files/input_boolean.yaml
input_select: !include config_files/input_select.yaml
input_number: !include config_files/input_number.yaml

### Set log level ###
logger:
  default: warning
  #log levels critical, fatal, error, warning, warn, info, debug, notset

### Http access setup ###
http:
  server_port: !secret hassio_server_port
  base_url: !secret hassio_ip
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret synology_ip
  ip_ban_enabled: true
  login_attempts_threshold: 20
  # 13-2-2019 RV: Deactivated SSL, because of reverse proxy setup on Synology NAS
  #ssl_certificate: !secret ssl_certificate_location
  #ssl_key: !secret ssl_key_location

### Enables default configuration options ### https://www.home-assistant.io/integrations/default_config/ 
default_config:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Zones
zone:
  name: Work Rens
  latitude: !secret work_rens_latitude
  longitude: !secret work_rens_longitude
  radius: 180
  icon: mdi:worker

# Weather
weather:
  - platform: buienradar
    name: 'station_home'
    forecast: true

# Sensors
sensor:
  # External IP Address
  - platform: dnsip
  # 2020-05-02 Replaced with standard integration from UI
  # Synology NAS statistics
  # - platform: synologydsm
  #   host: !secret synology_ip
  #   username: !secret synology_user
  #   password: !secret synology_password
  #   monitored_conditions:
  #     - cpu_total_load
  #     - memory_real_usage
  #     - network_up
  #     - network_down
  #     - disk_status
  #     - volume_size_used
  # Travis-CI Sensor for continues integration
  - platform: travisci
    api_key: !secret travis_token
    branch: master
    repository: HomeAssistant
  #  
  # Google Maps Travel Distance
  # Deactivated because of error: "REQUEST_DENIED (API keys with referer restrictions cannot be used with this API.)"
  # Need to activate the travel distance API in google console (add payment subscription)
  #- platform: google_travel_time
  #  name: Rens to Home
  #  api_key: !secret google_apikey_maps
  #  origin: !secret device_rens_geo
  #  destination: zone.home
  #  options:
  #    mode: driving
  #    language: nl


# Check if users are at home via netgear router connection 
device_tracker:
  - platform: netgear
    host: !secret router_ip
    username: !secret router_username
    password: !secret router_password
    # Check every minute for new devices
    interval_seconds: 60
    # Wait atleast 5 minutes before setting away status
    consider_home: 0:05
    new_device_defaults:
      track_new_devices: false # New devices won't be tracked by default -> change tracking per device in the known_devices.yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'nl'
    base_url: !secret hassio_url

# Components
climate:
  platform: nest

# Google Assistant
google_assistant:
  project_id: !secret google_projectid
  # api_key: !secret google_apikey  deprecated in 0.107
  service_account: !include GoogleAssistant-key.json
  expose_by_default: false
  entity_config:
    scene.gotosleep:
      name: Naar bed
      expose: true
      aliases:
        - Bedtijd
        - Ga slapen

# Nest Thermostat
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

# Xiaomi Roborock
vacuum:
  - platform: xiaomi_miio
    host: 192.168.2.28
    token: !secret roborock_token

# Tesla Model 3
tesla:
  username: !secret tesla_username
  password: !secret tesla_password

# Pushbullet
notify:
  - name: notify_pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_apikey

### Hass.io Database ###
# Recorder, controlling where the Logs / Activites are stored
recorder:
  # keep the last 2 weeks of data
  purge_keep_days: 14
  # automatically purge the database every night based on the purge_keep_days, default is true
  # auto_purge: true
  # The max amount of times, the recorder retries to connect to the database
  db_max_retries: 6
  #The time in seconds, that the recorder sleeps when trying to connect to the database
  db_retry_wait: 20
  # data is written to mariadb running on Synology NAS
  db_url: !secret mariadb_url
  # exclude the following entities of logging:
  # exclude:
  #  entities:
    # Excluding router sensors, deactivated didn't seem to work, so commented exlusion out.
     # - sensor.r7000_gateway_packets_sec_received
     # - sensor.r7000_gateway_bytes_received
     # - sensor.r7000_gateway_bytes_sent
     # - sensor.r7000_gateway_kbyte_sec_received
     # - sensor.r7000_gateway_packets_received
     # - sensor.r7000_gateway_kbyte_sec_sent
     # - sensor.r7000_gateway_packets_sec_sent
     # - sensor.r7000_gateway_packets_sent