# Additional automation file not configured via frontend
# So that '!secret' options are supported and not overwritten with actual values, see: https://github.com/home-assistant/frontend/issues/3065
- id: 'Alarm_ArmAway'
  alias: Alarm - Arm Away
  description: Activates alarm when nobody's at home for 5 minutes
  trigger:
  - platform: state
    entity_id: input_boolean.home_presence
    from: 'on'
    to: 'off'
    for: 00:05:00
  condition: []
  action:
  - service: alarm_control_panel.alarm_arm_away
    data:
      code: !secret hassio_alarm_code
    entity_id: alarm_control_panel.ha_alarm
  mode: single

- id: 'Alarm_ArmNight'
  alias: Alarm - Arm Night
  description: Activates alarm when going to bed
  trigger:
  - platform: state
    entity_id: input_boolean.sleeping
    from: 'off'
    to: 'on'
  action:
  - service: alarm_control_panel.alarm_arm_night
    data:
      code: !secret hassio_alarm_code
    entity_id: alarm_control_panel.ha_alarm
  mode: single

- id: 'Alarm_DisarmHome'
  alias: Alarm - Disarm Home
  description: Deactivates the alarm
  trigger:
  - platform: state # Somebody arrives home
    entity_id: input_boolean.home_presence
    from: 'off'
    to: 'on'
  - platform: event # Selected action from mobile device
    event_type: mobile_app_notification_action
    event_data:
      action: alarm_disarm
  condition: []
  action:
  - service: alarm_control_panel.alarm_disarm
    data:
      code: !secret hassio_alarm_code
    entity_id: alarm_control_panel.ha_alarm
  - service: homeassistant.turn_off
    entity_id:
      - media_player.nest_hub_woonkamer
      - media_player.google_home
  mode: single

- id: 'Alarm_DisarmWakeup'
  alias: Alarm - Disarm WakeUp
  description: Deactivates the alarm
  trigger:
  - platform: time
    at: 
      - sensor.pixel_6_next_alarm # Next alarm Phone Rens
      - sensor.oneplus8pro_next_alarm # Next alarm Phone Tas
  condition:
    - condition: state
      entity_id: input_boolean.home_presence
      state: 'on'
  action:
  - service: alarm_control_panel.alarm_disarm
    data:
      code: !secret hassio_alarm_code
    entity_id: alarm_control_panel.ha_alarm
  - service: homeassistant.turn_off
    entity_id:
      - media_player.nest_hub_woonkamer
      - media_player.google_home
  mode: single